---
# ArchiveSpace.yml ========================================
# default
archivesspace_backend_port: '8089'
archivesspace_frontend_port: '8080'
archivesspace_solr_port: '8090'
archivesspace_solr_core_path: '/collection1/'
archivesspace_username: admin
archivesspace_password: admin
archivesspace_host: localhost
# staging
archivesspace_host_staging: staging.archivesspace.yourorg.org
# production
archivesspace_host_production: archivesspace.yourorg.org
#==========================================================

# database.yml : MySQL ====================================
# default
# database_adapter: mysql2
# database_encoding: utf8
# database_pool: 5
# database_host: localhost
# database_username: circa
# database_password: circa
# # development
# database_development: circa
# # test
# database_test: circa_test
#==========================================================

# database.yml : SQLite =======================================
# default
database_adapter: sqlite3
database_pool: 5
database_timeout: 5000
# development
database_development: db/development.sqlite3
database_test: db/test.sqlite3
database_production: db/production.sqlite3
#==========================================================

# email.yml ===============================================
# default
order_notification_default_email: 'you@yourorg.org'
order_notification_digital_items_email: 'you@yourorg.org'
circa_email: 'circa@yourorg.org'
circa_email_display_name: 'Circa'
#==========================================================

# solr.yml ================================================
# default
solr_host: localhost
solr_port: '8983'
solr_core_name: 'circa'
solr_core_path: /solr/circa/
#==========================================================
